import { RecipeNutritionInput } from "@/types/nutrition";
// export const nutritionData: RecipeNutritionInput = {
//     title: "Makaron z truskawkami",
//     totalWeight: 1220,
//     per100g: {
//         calories: 109.8,
//         protein: 4.8,
//         fat: 2.1,
//         carbohydrate: 17.9,
//     },
//     micronutrients: {
//         vitaminA: 14,
//         vitaminC: 23.5,
//         vitaminD: 0,
//         vitaminE: 0.2,
//         vitaminK: 1.8,
//         vitaminB6: 0.05,
//         folate: 18,
//         calcium: 48,
//         iron: 0.4,
//         magnesium: 11,
//         potassium: 128,
//         sodium: 42,
//         zinc: 0.4,
//         selenium: 8.1,
//     },
// };
export const nutritionData: RecipeNutritionInput = {
    title: "Fasolka szparagowa z masłem i parmezanem",
    totalWeight: 497,
    per100g: {
        calories: 103.4,
        protein: 3.8,
        fat: 7.4,
        carbohydrate: 6.1,
    },
    micronutrients: {
        vitaminA: 38,
        vitaminC: 8.7,
        vitaminD: 0.2,
        vitaminE: 0.5,
        vitaminK: 25.6,
        vitaminB6: 0.08,
        folate: 35,
        calcium: 92,
        iron: 0.9,
        magnesium: 24,
        potassium: 210,
        sodium: 290,
        zinc: 0.7,
        selenium: 3.4,
    },
};
