import { RecipeNutritionInput } from "@/types/nutrition";
// export const nutritionData: RecipeNutritionInput = {
//     title: "Makaron z truskawkami",
//     totalWeight: 1220,
//     per100g: {
//         calories: 109.8,
//         protein: 4.8,
//         fat: 2.1,
//         carbohydrate: 17.9,
//     },
//     micronutrients: {
//         vitaminA: 14,
//         vitaminC: 23.5,
//         vitaminD: 0,
//         vitaminE: 0.2,
//         vitaminK: 1.8,
//         vitaminB6: 0.05,
//         folate: 18,
//         calcium: 48,
//         iron: 0.4,
//         magnesium: 11,
//         potassium: 128,
//         sodium: 42,
//         zinc: 0.4,
//         selenium: 8.1,
//     },
// };
export const nutritionData: RecipeNutritionInput = {
    title: "Wiosenna sałatka z kozim serem i truskawkami",
    totalWeight: 312,
    per100g: {
        calories: 208.6,
        protein: 6.4,
        fat: 16.8,
        carbohydrate: 10.4,
    },
    micronutrients: {
        vitaminA: 280,
        vitaminC: 31.5,
        vitaminD: 0.1,
        vitaminE: 3.2,
        vitaminK: 155,
        vitaminB6: 0.16,
        folate: 85,
        calcium: 125,
        iron: 2.1,
        magnesium: 55,
        potassium: 290,
        sodium: 310,
        zinc: 1.1,
        selenium: 4.8,
    },
};
