/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type RecipeComment = {
  _id: string
  _type: 'recipeComment'
  _createdAt: string
  _updatedAt: string
  _rev: string
  recipeId?: string
  parentId?: string
  content?: string
  author?: string
  isAdmin?: boolean
  createdAt?: string
  fingerprint?: string
  likes?: Array<string>
  shortComment?: {
    content?: string
    createdAt?: string
  }
}

export type RecipeNotes = {
  _id: string
  _type: 'recipeNotes'
  _createdAt: string
  _updatedAt: string
  _rev: string
  userId?: string
  recipe?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'recipe'
  }
  notes?: string
}

export type Favorite = {
  _id: string
  _type: 'favorite'
  _createdAt: string
  _updatedAt: string
  _rev: string
  userId?: string
  recipe?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'recipe'
  }
}

export type Options = {
  _id: string
  _type: 'options'
  _createdAt: string
  _updatedAt: string
  _rev: string
  fullSummary?: {
    products?: Array<string>
    dietary?: Array<string>
    cuisine?: Array<string>
    tags?: Array<string>
    title?: Array<string>
    source?: {
      url?: Array<string>
      book?: Array<string>
      title?: Array<string>
      author?: Array<string>
      where?: Array<string>
    }
  }
  goodSummary?: {
    products?: Array<string>
    dietary?: Array<string>
    cuisine?: Array<string>
    tags?: Array<string>
    title?: Array<string>
    source?: {
      http?: Array<string>
      book?: Array<string>
      title?: Array<string>
      author?: Array<string>
      where?: Array<string>
    }
  }
}

export type Recipe = {
  _id: string
  _type: 'recipe'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  description?: {
    title?: string
    content?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    image?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
    notes?: string
  }
  ingredients?: Array<{
    excluded?: boolean
    name?: string
    quantity?: number
    unit?: string
    _key: string
  }>
  ingredientsNotes?: string
  products?: Array<string>
  preparationSteps?: Array<{
    content?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'strong' | 'bullet' | 'number'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        openInNewTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    image?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
    notes?: string
    _key: string
  }>
  prepTime?: number
  cookTime?: number
  recipeYield?: number
  cuisine?: Array<string>
  dietary?: Array<string>
  tags?: Array<string>
  notes?: string
  kizia?: boolean
  status?: 'Good' | 'Acceptable' | 'Improvement' | 'Forget'
  source?: {
    url?: string
    book?: string
    title?: string
    author?: string
    where?: string
  }
  nutrition?: {
    per100g?: {
      calories?: number
      protein?: number
      fat?: number
      carbohydrate?: number
    }
    totalWeight?: number
    micronutrients?: {
      vitaminA?: number
      vitaminC?: number
      vitaminD?: number
      vitaminE?: number
      vitaminK?: number
      thiamin?: number
      riboflavin?: number
      niacin?: number
      vitaminB6?: number
      folate?: number
      vitaminB12?: number
      calcium?: number
      iron?: number
      magnesium?: number
      potassium?: number
      sodium?: number
      zinc?: number
      selenium?: number
    }
    calculatedAt?: string
    rawData?: string
  }
  ratings?: Array<{
    rating?: number
    fingerprint?: string
    updatedAt?: string
    _key: string
  }>
  ratingSummary?: {
    average?: number
    count?: number
  }
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | RecipeComment
  | RecipeNotes
  | Favorite
  | Options
  | Recipe
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
export declare const internalGroqTypeReferenceTo: unique symbol
