// export const comments = [];
export const comments = [
    {
        author: "NataliaKuchnia",
        parentId: null,
        content: "Bardzo przyjemny sposób na wykorzystanie truskawek. Sos wyszedł gładki, a połączenie z twarogiem waniliowym świetnie się sprawdziło.",
        createdAt: "2026-05-26T09:14:22.000Z",
        fingerprint: "fp_comment_1",
        likes: ["fp_comment_4", "fp_comment_9"],
        isAdmin: false,
        shortComment: {
            content: "Dziękujemy ❤️",
            createdAt: "2026-05-26T12:48:10.000Z",
        },
    },
    {
        author: "Marek_Smak",
        parentId: null,
        content: "Wyszło znakomicie. Cała rodzina zjadła bez marudzenia.",
        createdAt: "2026-05-26T13:37:05.000Z",
        fingerprint: "fp_comment_2",
        likes: [],
        isAdmin: false,
        shortComment: {
            content: "Miło nam",
            createdAt: "2026-05-26T15:03:11.000Z",
        },
    },
    {
        author: "Asia z Tychów",
        parentId: null,
        content: "Czy makaron można ugotować trochę wcześniej i wymieszać z sosem dopiero przed podaniem?",
        createdAt: "2026-05-26T17:26:40.000Z",
        fingerprint: "fp_comment_3",
        likes: [],
        isAdmin: false,
        shortComment: null,
    },
    {
        author: "DomowaŁyżka",
        parentId: null,
        content: "Zmniejszyłam odrobinę ilość cukru, bo truskawki były bardzo słodkie. Reszty proporcji trzymałam się dokładnie i efekt był bardzo udany.",
        createdAt: "2026-05-27T08:11:57.000Z",
        fingerprint: "fp_comment_4",
        likes: ["fp_comment_1"],
        isAdmin: false,
        shortComment: {
            content: "Dzięki 😊",
            createdAt: "2026-05-27T10:21:43.000Z",
        },
    },
    {
        author: "KrzysiekW",
        parentId: null,
        content: "Świetny przepis na szybki obiad.",
        createdAt: "2026-05-27T11:55:18.000Z",
        fingerprint: "fp_comment_5",
        likes: [],
        isAdmin: false,
        shortComment: {
            content: "Serdecznie dziękujemy",
            createdAt: "2026-05-27T13:20:09.000Z",
        },
    },
    {
        author: "Alicja89",
        parentId: null,
        content: "Najbardziej podoba mi się to, że sos nie jest ciężki. Sok z cytryny fajnie podkreśla smak truskawek.",
        createdAt: "2026-05-27T18:42:06.000Z",
        fingerprint: "fp_comment_6",
        likes: ["fp_comment_1"],
        isAdmin: false,
        shortComment: {
            content: "Cieszy nas",
            createdAt: "2026-05-28T08:17:55.000Z",
        },
    },
    {
        author: "Paweł_Gotuje",
        parentId: null,
        content: "Zrobiłem dokładnie według przepisu i wyszło za pierwszym razem.",
        createdAt: "2026-05-28T07:36:14.000Z",
        fingerprint: "fp_comment_7",
        likes: [],
        isAdmin: false,
        shortComment: {
            content: "Super 🙂",
            createdAt: "2026-05-28T09:01:03.000Z",
        },
    },
    {
        author: "MadziaM",
        parentId: null,
        content: "Dzieci poprosiły o dokładkę. Truskawkowy sos z twarogiem wyszedł bardzo kremowy.",
        createdAt: "2026-05-28T12:19:44.000Z",
        fingerprint: "fp_comment_8",
        likes: ["fp_comment_11"],
        isAdmin: false,
        shortComment: {
            content: "Dzięki!",
            createdAt: "2026-05-28T14:45:21.000Z",
        },
    },
    {
        author: "Tomek_K",
        parentId: null,
        content: "Bardzo udana propozycja na ciepłe dni.",
        createdAt: "2026-05-28T16:08:52.000Z",
        fingerprint: "fp_comment_9",
        likes: [],
        isAdmin: false,
        shortComment: {
            content: "Pozdrawiamy",
            createdAt: "2026-05-28T18:31:09.000Z",
        },
    },
    {
        author: "OlaNaWidoku",
        parentId: null,
        content: "Czy skrobię ziemniaczaną można dodać od razu do truskawek, czy lepiej wcześniej rozmieszać ją dokładnie w niewielkiej ilości płynu?",
        createdAt: "2026-05-29T09:04:37.000Z",
        fingerprint: "fp_comment_10",
        likes: [],
        isAdmin: false,
        shortComment: null,
    },
    {
        author: "SmakiAni",
        parentId: null,
        content: "Zwiększyłam nieco ilość truskawek względem makaronu, bo miałam ich naprawdę dużo. Bardzo smaczna wersja.",
        createdAt: "2026-05-29T11:51:28.000Z",
        fingerprint: "fp_comment_11",
        likes: ["fp_comment_8", "fp_comment_1"],
        isAdmin: false,
        shortComment: {
            content: "Miłego dnia",
            createdAt: "2026-05-29T16:42:00.000Z",
        },
    },
    {
        author: "RobertL",
        parentId: null,
        content: "Przepis zapisany do ulubionych.",
        createdAt: "2026-05-29T18:22:45.000Z",
        fingerprint: "fp_comment_12",
        likes: [],
        isAdmin: false,
        shortComment: {
            content: "Dziękujemy 🙂",
            createdAt: "2026-05-29T19:55:12.000Z",
        },
    },
    {
        author: "GosiaPiecze",
        parentId: null,
        content: "Smak bardzo dobry, ale następnym razem chwilę dłużej pogotuję sos, żeby był odrobinę gęstszy. Poza tym wszystko się zgadzało.",
        createdAt: "2026-05-30T08:47:20.000Z",
        fingerprint: "fp_comment_13",
        likes: ["fp_comment_16"],
        isAdmin: false,
        shortComment: {
            content: "Dzięki ❤️",
            createdAt: "2026-05-30T13:05:51.000Z",
        },
    },
    {
        author: "KasiaR",
        parentId: null,
        content: "Bardzo nam smakowało. Prosty skład i szybkie wykonanie.",
        createdAt: "2026-05-30T12:03:14.000Z",
        fingerprint: "fp_comment_14",
        likes: [],
        isAdmin: false,
        shortComment: {
            content: "Cieszymy się",
            createdAt: "2026-05-30T17:14:30.000Z",
        },
    },
    {
        author: "Łukasz z Opola",
        parentId: null,
        content: "Pierwszy raz robiłem makaron z truskawkami w takiej wersji i byłem pozytywnie zaskoczony. Twaróg waniliowy dobrze równoważy całość.",
        createdAt: "2026-05-31T09:29:33.000Z",
        fingerprint: "fp_comment_15",
        likes: ["fp_comment_1"],
        isAdmin: false,
        shortComment: {
            content: "Bardzo miło",
            createdAt: "2026-05-31T11:07:02.000Z",
        },
    },
    {
        author: "JagodaGotuje",
        parentId: null,
        content: "U mnie sprawdziło się dodanie nieco większej ilości soku z cytryny. Lubię bardziej wyrazisty owocowy smak.",
        createdAt: "2026-05-31T14:12:17.000Z",
        fingerprint: "fp_comment_16",
        likes: ["fp_comment_13"],
        isAdmin: false,
        shortComment: {
            content: "Dziękujemy!",
            createdAt: "2026-05-31T18:33:58.000Z",
        },
    },
    {
        author: "Michał_B",
        parentId: null,
        content: "Rewelacyjne połączenie składników 😊",
        createdAt: "2026-05-31T19:54:41.000Z",
        fingerprint: "fp_comment_17",
        likes: [],
        isAdmin: false,
        shortComment: {
            content: "❤️",
            createdAt: "2026-06-01T08:05:44.000Z",
        },
    },
    {
        author: "EwaDomowo",
        parentId: null,
        content: "Czy można przygotować sos wcześniej i przechować go kilka godzin w lodówce?",
        createdAt: "2026-06-01T10:21:09.000Z",
        fingerprint: "fp_comment_18",
        likes: [],
        isAdmin: false,
        shortComment: null,
    },
    {
        author: "Przepisownik",
        parentId: null,
        content: "Dokładnie tego szukałem na sezon truskawkowy.",
        createdAt: "2026-06-01T15:16:30.000Z",
        fingerprint: "fp_comment_19",
        likes: [],
        isAdmin: false,
        shortComment: {
            content: "Dzięki 🙂",
            createdAt: "2026-06-01T18:27:01.000Z",
        },
    },
    {
        author: "KarolinaK",
        parentId: null,
        content: "Przygotowałam na szybki obiad po pracy. Najwięcej czasu zajęło oczyszczenie truskawek, samo wykonanie było bardzo proste.",
        createdAt: "2026-06-02T11:08:56.000Z",
        fingerprint: "fp_comment_20",
        likes: ["fp_comment_24"],
        isAdmin: false,
        shortComment: {
            content: "Miło nam ❤️",
            createdAt: "2026-06-02T15:46:22.000Z",
        },
    },
    {
        author: "Norbert76",
        parentId: null,
        content: "Bardzo udany przepis.",
        createdAt: "2026-06-03T08:43:12.000Z",
        fingerprint: "fp_comment_21",
        likes: [],
        isAdmin: false,
        shortComment: {
            content: "Dziękujemy",
            createdAt: "2026-06-03T09:52:00.000Z",
        },
    },
    {
        author: "BasiaOdŚniadań",
        parentId: null,
        content: "Makaron ugotowany al dente sprawdził się tutaj świetnie. Całość zniknęła z talerzy błyskawicznie.",
        createdAt: "2026-06-03T17:22:38.000Z",
        fingerprint: "fp_comment_22",
        likes: ["fp_comment_1", "fp_comment_11"],
        isAdmin: false,
        shortComment: {
            content: "Super ❤️",
            createdAt: "2026-06-04T08:11:15.000Z",
        },
    },
    {
        author: "Monika_L",
        parentId: null,
        content: "Smakowało wszystkim. Na pewno wrócę do tego przepisu.",
        createdAt: "2026-06-04T12:10:42.000Z",
        fingerprint: "fp_comment_23",
        likes: [],
        isAdmin: false,
        shortComment: {
            content: "Dzięki 😊",
            createdAt: "2026-06-04T14:22:33.000Z",
        },
    },
    {
        author: "SzymonGotuje",
        parentId: null,
        content: "Bardzo prosty, sezonowy obiad. Truskawki i twaróg waniliowy tworzą naprawdę zgrany duet.",
        createdAt: "2026-06-05T08:28:50.000Z",
        fingerprint: "fp_comment_24",
        likes: ["fp_comment_20", "fp_comment_1", "fp_comment_22"],
        isAdmin: false,
        shortComment: {
            content: "Serdeczne dzięki",
            createdAt: "2026-06-05T10:18:40.000Z",
        },
    },
];
