export const comments = [
    {
        author: "debik78",
        parentId: null,
        content: "Super!",
        createdAt: "2026-04-24T08:40:22.000Z",
        fingerprint: "fp_comment_1",
        likes: [],
        isAdmin: false,
        shortComment: {
            content: "Dzięki ❤️",
            createdAt: "2026-04-24T09:35:15.000Z",
        },
    },
    {
        author: "ToniJoHenry",
        parentId: null,
        content: "Pyszne! Cienko rozwałkowane wychodzą idealnie.",
        createdAt: "2026-04-24T15:10:45.000Z",
        fingerprint: "fp_comment_2",
        likes: ["fp_comment_1"],
        isAdmin: false,
        shortComment: {
            content: "Super 🙂",
            createdAt: "2026-04-24T16:25:30.000Z",
        },
    },
    {
        author: "nanak",
        parentId: null,
        content: "Rewelacja!",
        createdAt: "2026-04-25T10:55:19.000Z",
        fingerprint: "fp_comment_3",
        likes: [],
        isAdmin: false,
        shortComment: {
            content: "Cieszy nas 😊",
            createdAt: "2026-04-25T12:20:40.000Z",
        },
    },
    {
        author: "rubia",
        parentId: null,
        content: "Mniam! Odpoczęte kulki łatwiej się wałkują.",
        createdAt: "2026-04-25T17:45:33.000Z",
        fingerprint: "fp_comment_4",
        likes: ["fp_comment_2"],
        isAdmin: false,
        shortComment: {
            content: "Dziękuję!",
            createdAt: "2026-04-25T19:10:22.000Z",
        },
    },
    {
        author: "ewelinajiao",
        parentId: null,
        content: "Czy oliwa zamiast masła też dobrze działa?",
        createdAt: "2026-04-26T09:30:50.000Z",
        fingerprint: "fp_comment_5",
        likes: [],
        isAdmin: false,
        shortComment: null,
    },
    {
        author: "Avalo",
        parentId: null,
        content: "Wyszło super",
        createdAt: "2026-04-26T16:35:12.000Z",
        fingerprint: "fp_comment_6",
        likes: ["fp_comment_3"],
        isAdmin: false,
        shortComment: {
            content: "Miło nam",
            createdAt: "2026-04-26T18:05:44.000Z",
        },
    },
    {
        author: "TNT",
        parentId: null,
        content: "Bosko! Smażenie na suchej patelni bez tłuszczu genialne.",
        createdAt: "2026-04-27T11:45:28.000Z",
        fingerprint: "fp_comment_7",
        likes: [],
        isAdmin: false,
        shortComment: {
            content: "Dzięki ❤️",
            createdAt: "2026-04-27T13:20:19.000Z",
        },
    },
    {
        author: "Olenika92",
        parentId: null,
        content: "Hit!",
        createdAt: "2026-04-28T14:15:37.000Z",
        fingerprint: "fp_comment_8",
        likes: ["fp_comment_4"],
        isAdmin: false,
        shortComment: {
            content: "Super 🙂",
            createdAt: "2026-04-28T15:40:55.000Z",
        },
    },
    {
        author: "Halina",
        parentId: null,
        content: "Bardzo smaczne, przykryte ściereczką zostają miękkie.",
        createdAt: "2026-04-29T10:50:22.000Z",
        fingerprint: "fp_comment_9",
        likes: ["fp_comment_6", "fp_comment_7"],
        isAdmin: false,
        shortComment: {
            content: "Pozdrawiamy",
            createdAt: "2026-04-29T12:25:10.000Z",
        },
    },
    {
        author: "Maria Izabela",
        parentId: null,
        content: "Dziękuję!",
        createdAt: "2026-05-01T12:55:40.000Z",
        fingerprint: "fp_comment_10",
        likes: [],
        isAdmin: false,
        shortComment: {
            content: "Dzięki 😊",
            createdAt: "2026-05-01T14:30:28.000Z",
        },
    },
    {
        author: "Patrycja Lewandowska",
        parentId: null,
        content: "Czy można zamrozić gotowe tortille?",
        createdAt: "2026-05-02T18:45:15.000Z",
        fingerprint: "fp_comment_11",
        likes: [],
        isAdmin: false,
        shortComment: null,
    },
    {
        author: "Radosław",
        parentId: null,
        content: "Pycha dziękuję",
        createdAt: "2026-05-03T15:05:33.000Z",
        fingerprint: "fp_comment_12",
        likes: ["fp_comment_9"],
        isAdmin: false,
        shortComment: {
            content: "Cieszy nas",
            createdAt: "2026-05-03T16:50:19.000Z",
        },
    },
    {
        author: "Ewusia1222",
        parentId: null,
        content: "Rozwałkowałam najcieniej jak się da - perfekt.",
        createdAt: "2026-05-05T11:55:50.000Z",
        fingerprint: "fp_comment_13",
        likes: [],
        isAdmin: false,
        shortComment: {
            content: "Super 🙂",
            createdAt: "2026-05-05T13:30:37.000Z",
        },
    },
    {
        author: "lukas.kar",
        parentId: null,
        content: "Idealny przepis",
        createdAt: "2026-05-07T19:55:22.000Z",
        fingerprint: "fp_comment_14",
        likes: ["fp_comment_10"],
        isAdmin: false,
        shortComment: {
            content: "Dzięki ❤️",
            createdAt: "2026-05-07T21:25:40.000Z",
        },
    },
    {
        author: "bsylvia",
        parentId: null,
        content: "Polecam!",
        createdAt: "2026-05-10T13:35:19.000Z",
        fingerprint: "fp_comment_15",
        likes: [],
        isAdmin: false,
        shortComment: {
            content: "Miło nam",
            createdAt: "2026-05-10T15:10:55.000Z",
        },
    },
    {
        author: "fiziowaaa",
        parentId: null,
        content: "Proszek do pieczenia + odpoczynek = elastyczne placki.",
        createdAt: "2026-05-12T17:10:44.000Z",
        fingerprint: "fp_comment_16",
        likes: ["fp_comment_13"],
        isAdmin: false,
        shortComment: {
            content: "Dzięki 😊",
            createdAt: "2026-05-12T18:45:28.000Z",
        },
    },
    {
        author: "Rene",
        parentId: null,
        content: "Robiłam już wielokrotnie",
        createdAt: "2026-05-15T10:20:37.000Z",
        fingerprint: "fp_comment_17",
        likes: [],
        isAdmin: false,
        shortComment: {
            content: "Super",
            createdAt: "2026-05-15T12:05:19.000Z",
        },
    },
    {
        author: "Marzenna",
        parentId: null,
        content: "Czy bez proszku do pieczenia też się uda?",
        createdAt: "2026-05-18T14:55:28.000Z",
        fingerprint: "fp_comment_18",
        likes: [],
        isAdmin: false,
        shortComment: null,
    },
    {
        author: "Natalia Kowalska",
        parentId: null,
        content: "Miękkie i elastyczne.",
        createdAt: "2026-05-22T18:05:50.000Z",
        fingerprint: "fp_comment_19",
        likes: ["fp_comment_14", "fp_comment_16"],
        isAdmin: false,
        shortComment: {
            content: "Pozdrawiamy",
            createdAt: "2026-05-22T19:40:33.000Z",
        },
    },
    {
        author: "Pafwvcio",
        parentId: null,
        content: "Boskie!",
        createdAt: "2026-05-28T11:45:12.000Z",
        fingerprint: "fp_comment_20",
        likes: [],
        isAdmin: false,
        shortComment: {
            content: "Dziękuję ❤️",
            createdAt: "2026-05-28T13:20:55.000Z",
        },
    },
];
