export const comments = [
    {
        author: "anna92pl",
        parentId: null,
        content: "Pycha! 🌟",
        createdAt: "2026-04-23T18:45:12.000Z",
        fingerprint: "fp_comment_1",
        likes: [],
        isAdmin: false,
        shortComment: {
            content: "Dziękuję ❤️",
            createdAt: "2026-04-23T19:10:45.000Z",
        },
    },
    {
        author: "tomek1987",
        parentId: null,
        content: "Super prosty i smaczny przepis Piotrze!",
        createdAt: "2026-04-24T09:22:33.000Z",
        fingerprint: "fp_comment_2",
        likes: ["fp_comment_1"],
        isAdmin: false,
        shortComment: {
            content: "Miło nam 😊",
            createdAt: "2026-04-24T10:05:19.000Z",
        },
    },
    {
        author: "monika_kk",
        parentId: null,
        content: "Wyśmienite!",
        createdAt: "2026-04-24T12:15:47.000Z",
        fingerprint: "fp_comment_3",
        likes: [],
        isAdmin: false,
        shortComment: {
            content: "Dzięki! 🙂",
            createdAt: "2026-04-24T13:40:22.000Z",
        },
    },
    {
        author: "kasia_85",
        parentId: null,
        content: "Ugotowałam. Masło z parmezanem idealnie oblepiło warzywa. Rodzina pochłonęła w minutę!",
        createdAt: "2026-04-25T17:33:09.000Z",
        fingerprint: "fp_comment_4",
        likes: ["fp_comment_2", "fp_comment_3"],
        isAdmin: false,
        shortComment: {
            content: "Super 🙂",
            createdAt: "2026-04-25T18:12:55.000Z",
        },
    },
    {
        author: "pawel_ziel",
        parentId: null,
        content: "Mega!",
        createdAt: "2026-04-26T11:08:41.000Z",
        fingerprint: "fp_comment_5",
        likes: [],
        isAdmin: false,
        shortComment: {
            content: "Cieszy nas",
            createdAt: "2026-04-26T11:45:30.000Z",
        },
    },
    {
        author: "ola_mw",
        parentId: null,
        content: "Czy można użyć mniej masła? Zawsze staram się trochę odchudzać dania.",
        createdAt: "2026-04-27T14:55:22.000Z",
        fingerprint: "fp_comment_6",
        likes: [],
        isAdmin: false,
        shortComment: null,
    },
    {
        author: "marek_kr",
        parentId: null,
        content: "Boskie",
        createdAt: "2026-04-28T19:40:15.000Z",
        fingerprint: "fp_comment_7",
        likes: ["fp_comment_4"],
        isAdmin: false,
        shortComment: {
            content: "Dziękuję ❤️",
            createdAt: "2026-04-28T20:05:50.000Z",
        },
    },
    {
        author: "natalia_b",
        parentId: null,
        content: "Przygotowałam jako warzywo do obiadu z kurczakiem. Wyszła idealnie miękka i aromatyczna.",
        createdAt: "2026-04-29T08:17:44.000Z",
        fingerprint: "fp_comment_8",
        likes: [],
        isAdmin: false,
        shortComment: {
            content: "Pozdrawiamy",
            createdAt: "2026-04-29T09:30:12.000Z",
        },
    },
    {
        author: "krzysztof_p",
        parentId: null,
        content: "Genialne!",
        createdAt: "2026-05-01T16:22:58.000Z",
        fingerprint: "fp_comment_9",
        likes: [],
        isAdmin: false,
        shortComment: {
            content: "Dzięki 😊",
            createdAt: "2026-05-01T17:10:05.000Z",
        },
    },
    {
        author: "ewa_mw",
        parentId: null,
        content: "Dodałam odrobinę więcej parmezanu bo lubię i było jeszcze lepszej. Dzięki za prosty przepis!",
        createdAt: "2026-05-03T13:45:19.000Z",
        fingerprint: "fp_comment_10",
        likes: ["fp_comment_8"],
        isAdmin: false,
        shortComment: {
            content: "Super 🙂",
            createdAt: "2026-05-03T14:20:33.000Z",
        },
    },
    {
        author: "robert_77",
        parentId: null,
        content: "Smakowało świetnie.",
        createdAt: "2026-05-05T10:55:37.000Z",
        fingerprint: "fp_comment_11",
        likes: [],
        isAdmin: false,
        shortComment: {
            content: "Miło nam",
            createdAt: "2026-05-05T11:40:21.000Z",
        },
    },
    {
        author: "zuzia_94",
        parentId: null,
        content: "Czy fasolkę szparagową trzeba koniecznie namoczyć przed gotowaniem?",
        createdAt: "2026-05-07T15:30:12.000Z",
        fingerprint: "fp_comment_12",
        likes: [],
        isAdmin: false,
        shortComment: null,
    },
    {
        author: "janek_33",
        parentId: null,
        content: "Pyszności! 🔥",
        createdAt: "2026-05-10T19:12:45.000Z",
        fingerprint: "fp_comment_13",
        likes: ["fp_comment_10"],
        isAdmin: false,
        shortComment: {
            content: "Dziękuję ❤️",
            createdAt: "2026-05-10T20:05:18.000Z",
        },
    },
    {
        author: "magda_28",
        parentId: null,
        content: "Szybko, prosto i efektownie. Idealny dodatek.",
        createdAt: "2026-05-12T12:40:28.000Z",
        fingerprint: "fp_comment_14",
        likes: [],
        isAdmin: false,
        shortComment: {
            content: "Cieszy nas",
            createdAt: "2026-05-12T13:15:47.000Z",
        },
    },
    {
        author: "sylwia_k",
        parentId: null,
        content: "Super!",
        createdAt: "2026-05-15T17:08:55.000Z",
        fingerprint: "fp_comment_15",
        likes: [],
        isAdmin: false,
        shortComment: {
            content: "Dzięki! 🙂",
            createdAt: "2026-05-15T17:50:33.000Z",
        },
    },
    {
        author: "bartek_82",
        parentId: null,
        content: "Wyszła idealnie. Podawałem na gorąco jak w przepisie.",
        createdAt: "2026-05-18T20:25:41.000Z",
        fingerprint: "fp_comment_16",
        likes: ["fp_comment_14"],
        isAdmin: false,
        shortComment: {
            content: "Pozdrawiamy",
            createdAt: "2026-05-18T21:10:09.000Z",
        },
    },
    {
        author: "wera_91",
        parentId: null,
        content: "Dobre.",
        createdAt: "2026-05-22T11:33:17.000Z",
        fingerprint: "fp_comment_17",
        likes: [],
        isAdmin: false,
        shortComment: {
            content: "Miło nam 😊",
            createdAt: "2026-05-22T12:05:44.000Z",
        },
    },
    {
        author: "dawid_pl",
        parentId: null,
        content: "Czy można zamrozić gotową fasolkę",
        createdAt: "2026-05-25T14:47:29.000Z",
        fingerprint: "fp_comment_18",
        likes: [],
        isAdmin: false,
        shortComment: null,
    },
    {
        author: "patrycja_25",
        parentId: null,
        content: "Obłędne! 👌",
        createdAt: "2026-05-28T18:55:03.000Z",
        fingerprint: "fp_comment_19",
        likes: ["fp_comment_16"],
        isAdmin: false,
        shortComment: {
            content: "Dziękuję ❤️",
            createdAt: "2026-05-28T19:30:27.000Z",
        },
    },
    {
        author: "andrzej_k",
        parentId: null,
        content: "Prosty przepis, a efekt wow. Będę powtarzać.",
        createdAt: "2026-06-02T09:40:18.000Z",
        fingerprint: "fp_comment_20",
        likes: [],
        isAdmin: false,
        shortComment: {
            content: "Super 🙂",
            createdAt: "2026-06-02T10:15:52.000Z",
        },
    },
    {
        author: "karolina88",
        parentId: null,
        content: "Smakowało.",
        createdAt: "2026-06-05T16:12:44.000Z",
        fingerprint: "fp_comment_21",
        likes: [],
        isAdmin: false,
        shortComment: {
            content: "Dzięki 😊",
            createdAt: "2026-06-05T16:55:19.000Z",
        },
    },
    {
        author: "michal_45",
        parentId: null,
        content: "Następnym razem spróbuję dłużej podsmażyć, ale i tak wyszło super.",
        createdAt: "2026-06-08T13:27:51.000Z",
        fingerprint: "fp_comment_22",
        likes: ["fp_comment_20"],
        isAdmin: false,
        shortComment: {
            content: "Cieszy nas",
            createdAt: "2026-06-08T14:10:33.000Z",
        },
    },
    {
        author: "laura_19",
        parentId: null,
        content: "Pyszne",
        createdAt: "2026-06-12T19:18:29.000Z",
        fingerprint: "fp_comment_23",
        likes: [],
        isAdmin: false,
        shortComment: {
            content: "Pozdrawiamy",
            createdAt: "2026-06-12T20:05:41.000Z",
        },
    },
    {
        author: "seba_22",
        parentId: null,
        content: "Czy sól dodajemy tylko na końcu?",
        createdAt: "2026-06-15T10:45:37.000Z",
        fingerprint: "fp_comment_24",
        likes: [],
        isAdmin: false,
        shortComment: null,
    },
    {
        author: "agnieszka_7",
        parentId: null,
        content: "Najlepsza fasolka szparagowa jaką jadłam.",
        createdAt: "2026-06-20T17:33:12.000Z",
        fingerprint: "fp_comment_25",
        likes: ["fp_comment_22", "fp_comment_23"],
        isAdmin: false,
        shortComment: {
            content: "Dziękuję ❤️",
            createdAt: "2026-06-20T18:20:55.000Z",
        },
    },
    {
        author: "filip_34",
        parentId: null,
        content: "Dzięki Piotrze za przepis.",
        createdAt: "2026-06-25T08:55:44.000Z",
        fingerprint: "fp_comment_26",
        likes: [],
        isAdmin: false,
        shortComment: {
            content: "Miło nam",
            createdAt: "2026-06-25T09:40:12.000Z",
        },
    },
    {
        author: "joanna_mw",
        parentId: null,
        content: "Świetne!",
        createdAt: "2026-07-01T15:10:29.000Z",
        fingerprint: "fp_comment_27",
        likes: [],
        isAdmin: false,
        shortComment: {
            content: "Dzięki! 🙂",
            createdAt: "2026-07-01T15:55:47.000Z",
        },
    },
    {
        author: "grzegorz_51",
        parentId: null,
        content: "Udało się idealnie, petarda.",
        createdAt: "2026-07-08T20:40:15.000Z",
        fingerprint: "fp_comment_28",
        likes: ["fp_comment_25"],
        isAdmin: false,
        shortComment: {
            content: "Super 🙂",
            createdAt: "2026-07-08T21:15:33.000Z",
        },
    },
];
